# Generated by Django 2.0.10 on 2019-02-09 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('short_description', models.CharField(blank=True, max_length=1000, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('event_type', models.CharField(blank=True, choices=[('technical', 'Technical'), ('non-technical', 'Non-Technical')], max_length=50, null=True)),
                ('fee', models.IntegerField(default=50)),
                ('participation_type', models.CharField(blank=True, choices=[('individual', 'Individual'), ('team', 'Team')], max_length=50, null=True)),
                ('max_participation_in_team', models.IntegerField(blank=True, null=True)),
                ('total_participants', models.IntegerField(default=0)),
                ('coordinators', models.ManyToManyField(related_name='coordinators', to=settings.AUTH_USER_MODEL)),
                ('leader1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader1', to=settings.AUTH_USER_MODEL)),
                ('leader2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('university', models.CharField(blank=True, choices=[('gtu', 'Gujarat Technological University'), ('marwadi', 'Marwadi University'), ('atmiya', 'Atmiya University'), ('rk', 'RK University'), ('others', 'Others')], max_length=50, null=True)),
                ('enrolment_number', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('email_id', models.EmailField(blank=True, max_length=254, null=True)),
                ('participated', models.NullBooleanField()),
                ('winner', models.NullBooleanField()),
                ('place_secured', models.IntegerField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='events.Event')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
    ]
