# Generated by Django 2.0.10 on 2019-02-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='college',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='participation_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
