# Generated by Django 2.0.10 on 2019-02-09 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_auto_20190209_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='campaigner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='participant',
            name='participation_code',
            field=django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=4, lowercase=True, unique=True),
        ),
    ]
